// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGHgz9q3EIB2qKYad37nFE-0VLvUOSEXs',
    appId: '1:345187094229:web:6fafbbd3af344961b8dc5c',
    messagingSenderId: '345187094229',
    projectId: 'myportfolio-9891d',
    authDomain: 'myportfolio-9891d.firebaseapp.com',
    storageBucket: 'myportfolio-9891d.firebasestorage.app',
    measurementId: 'G-KWQP2C9NY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAVgdUzll8Mvh-TxN1YwqfeUS2phq8BY8',
    appId: '1:345187094229:android:1d89627b66964d78b8dc5c',
    messagingSenderId: '345187094229',
    projectId: 'myportfolio-9891d',
    storageBucket: 'myportfolio-9891d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWIjXLG5lk3zR2GuRHoclxrslBy2nD95Y',
    appId: '1:345187094229:ios:30e250697a2b3969b8dc5c',
    messagingSenderId: '345187094229',
    projectId: 'myportfolio-9891d',
    storageBucket: 'myportfolio-9891d.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );
}
